% Create stepped shaft from new image analysis
% 根据新图片分析创建4段阶梯实心轴
%
% 图片分析特征（Shaft_sample.png）：
% - 4段阶梯轴
% - 从左到右直径：65 -> 48 -> 55 -> 70 mm
% - 各段长度：35 -> 90 -> 70 -> 30 mm
% - 总长度：225 mm
% - 全部实心（ID=0）
%
% Author: Generated by Claude Code
% Date: 2026-01-31

clc
clear
close all

%% 轴参数定义（从新图片提取）
fprintf('========================================\n');
fprintf('轴参数定义（从新图片提取）\n');
fprintf('========================================\n');
fprintf('类型: 4段阶梯实心轴\n');
fprintf('总长度: 225 mm\n');
fprintf('直径范围: 48-70 mm\n\n');

fprintf('各段参数：\n');
fprintf('  第1段: 长度=35mm, 外径=65mm\n');
fprintf('  第2段: 长度=90mm, 外径=48mm\n');
fprintf('  第3段: 长度=70mm, 外径=55mm\n');
fprintf('  第4段: 长度=30mm, 外径=70mm\n\n');

%% 输入参数
% 定义轴的几何参数（4段阶梯轴）
inputShaft.Length = [35; 125; 195; 225];      % 各段结束位置 [mm]
inputShaft.ID = [[0, 0]; [0, 0]; [0, 0]; [0, 0]];  % 全部实心
inputShaft.OD = [[65, 65]; [48, 48]; [55, 55]; [70, 70]];  % 各段外径 [mm]

%% 可选参数
paramsShaft = struct();
paramsShaft.Name = 'SteppedShaft_ImageBased';  % 轴名称
paramsShaft.Order = 1;          % 单元阶次：1=一阶，2=二阶
paramsShaft.E_Revolve = 48;     % 旋转划分数（圆周分段）
paramsShaft.Beam_N = 16;         % 梁截面圆周分段数
paramsShaft.N_Slice = 50;        % 切片数量
paramsShaft.Meshsize = 3;         % 网格尺寸 [mm]
paramsShaft.Echo = 1;            % 打印信息

%% 创建轴对象
fprintf('========================================\n');
fprintf('创建轴对象...\n');
fprintf('========================================\n');
obj = shaft.Commonshaft(paramsShaft, inputShaft);

%% 求解
fprintf('========================================\n');
fprintf('求解中...\n');
fprintf('========================================\n');
obj = obj.solve();

%% 绘图
fprintf('========================================\n');
fprintf('绘制图形...\n');
fprintf('========================================\n');

% 2D截面图
fprintf('绘制2D截面...\n');
Plot2D(obj);

% 3D图形（显示整个轴）
fprintf('绘制3D模型...\n');
Plot3D(obj);

% 绘制每一段的外表面
fprintf('绘制各段外表面...\n');
for i = 1:4
    Plot3D(obj, 'faceno', 100 + i);
end

%% 网格信息
fprintf('========================================\n');
fprintf('网格统计信息\n');
fprintf('========================================\n');
fprintf('节点数: %d\n', size(obj.output.SolidMesh.Vert, 1));
fprintf('面数: %d\n', size(obj.output.SolidMesh.Face, 1));
fprintf('切片数: %d\n', size(obj.output.Node, 1));

%% 截面信息
fprintf('========================================\n');
fprintf('轴截面信息（沿轴向）\n');
fprintf('========================================\n');
fprintf('位置(mm)\t内径(mm)\t外径(mm)\t半径(mm)\t段\n');
fprintf('------------------------------------------------------------\n');
for i = 1:5:size(obj.output.Node, 1)
    pos = obj.output.Node(i);
    id = obj.output.ID(i);
    od = obj.output.OD(i);
    r = od / 2;

    % 判断所在段
    if pos <= 35
        sec = '第1段';
    elseif pos <= 125
        sec = '第2段';
    elseif pos <= 195
        sec = '第3段';
    else
        sec = '第4段';
    end

    fprintf('%.1f\t\t%.2f\t\t%.2f\t\t%.2f\t\t%s\n', pos, id, od, r, sec);
end

%% 获取材料信息
fprintf('========================================\n');
fprintf('材料信息\n');
fprintf('========================================\n');
fprintf('材料名称: %s\n', obj.params.Material.Name);
fprintf('密度: %.2e kg/mm^3\n', obj.params.Material.Dens);
fprintf('弹性模量: %.2e MPa\n', obj.params.Material.E);
fprintf('泊松比: %.3f\n', obj.params.Material.v);
fprintf('热膨胀系数: %.2e /K\n', obj.params.Material.a);

%% 边界标记说明
fprintf('========================================\n');
fprintf('边界标记说明\n');
fprintf('========================================\n');
fprintf('101: 第1段外表面 (D=65mm, x=0-35mm)\n');
fprintf('102: 第2段外表面 (D=48mm, x=35-125mm)\n');
fprintf('103: 第3段外表面 (D=55mm, x=125-195mm)\n');
fprintf('104: 第4段外表面 (D=70mm, x=195-225mm)\n');
fprintf('301: 左端面 (x=0mm)\n');
fprintf('305: 第1-2段阶梯面 (x=35mm)\n');
fprintf('306: 第2-3段阶梯面 (x=125mm)\n');
fprintf('307: 第3-4段阶梯面 (x=195mm)\n');
fprintf('308: 右端面 (x=225mm)\n\n');

%% 输出STL文件
fprintf('========================================\n');
fprintf('输出STL文件...\n');
fprintf('========================================\n');
OutputSTL(obj);

%% 计算轴的物理参数
fprintf('========================================\n');
fprintf('物理参数计算\n');
fprintf('========================================\n');

% 各段体积和重量
r1 = 65/2; r2 = 48/2; r3 = 55/2; r4 = 70/2;
L1 = 35; L2 = 90; L3 = 70; L4 = 30;

V1 = pi * r1^2 * L1;
V2 = pi * r2^2 * L2;
V3 = pi * r3^2 * L3;
V4 = pi * r4^2 * L4;
V_total = V1 + V2 + V3 + V4;

fprintf('第1段体积: %.2e mm^3 = %.2f cm^3\n', V1, V1/1000);
fprintf('第2段体积: %.2e mm^3 = %.2f cm^3\n', V2, V2/1000);
fprintf('第3段体积: %.2e mm^3 = %.2f cm^3\n', V3, V3/1000);
fprintf('第4段体积: %.2e mm^3 = %.2f cm^3\n', V4, V4/1000);
fprintf('总体积: %.2e mm^3 = %.2f cm^3\n', V_total, V_total/1000);

% 计算质量
rho = obj.params.Material.Dens * 1e9; % kg/mm^3 -> kg/cm^3
mass = V_total * obj.params.Material.Dens;
fprintf('材料密度: %.2f g/cm^3\n', rho);
fprintf('轴质量: %.2f g = %.2f kg\n', mass/1000, mass);

%% 完成信息
fprintf('========================================\n');
fprintf('轴创建完成！\n');
fprintf('========================================\n');
fprintf('轴名称: %s\n', obj.params.Name);
fprintf('STL文件: %s.stl\n', obj.params.Name);
fprintf('总质量: %.2f kg\n', mass);
fprintf('========================================\n');

%% 创建综合视图
figure('Position', [50, 50, 1400, 400]);

% 2D截面
subplot(1, 3, 1);
Plot(obj.output.Surface);
title('2D截面图');
axis equal;
grid on;

% 3D模型
subplot(1, 3, 2);
PlotFace(obj.output.SolidMesh);
title('3D实体模型');
axis equal;
grid on;
view(3);

% 3D模型（侧视图）
subplot(1, 3, 3);
PlotFace(obj.output.SolidMesh);
title('3D实体模型（侧视图）');
axis equal;
grid on;
view(0, 0);

%% 生成截面变化图
figure('Position', [100, 100, 1200, 800]);

x = obj.output.Node;
y_outer = obj.output.OD;
y_inner = obj.output.ID;
r_outer = y_outer / 2;

% 外径沿轴向分布
subplot(3, 1, 1);
plot(x, y_outer, 'b-o', 'LineWidth', 2, 'MarkerSize', 6);
grid on;
xlabel('轴向位置 (mm)');
ylabel('外径 (mm)');
title('外径沿轴向分布');
axis tight;

% 半径沿轴向分布
subplot(3, 1, 2);
plot(x, r_outer, 'r-s', 'LineWidth', 2, 'MarkerSize', 8);
grid on;
xlabel('轴向位置 (mm)');
ylabel('半径 (mm)');
title('半径沿轴向分布');
axis tight;

% 内外径对比
subplot(3, 1, 3);
plot(x, y_outer, 'b-o', 'LineWidth', 2, 'MarkerSize', 6);
hold on;
plot(x, y_inner, 'r--', 'LineWidth', 1.5);
grid on;
xlabel('轴向位置 (mm)');
ylabel('直径 (mm)');
title('内/外径沿轴向变化');
legend('外径', '内径', 'Location', 'best');
axis tight;

%% 边界条件示例代码
fprintf('========================================\n');
fprintf('边界条件示例代码\n');
fprintf('========================================\n');
fprintf('%% 示例1：两端简支\n');
fprintf('Ass = obj.output.Assembly;\n');
fprintf('Ass = AddBoundary(Ass, 1, ''No'', 301);\n');
fprintf('Bound1 = [0, 0, 1, 0, 0, 0];\n');
fprintf('Ass = SetBoundaryType(Ass, 1, Bound1);\n\n');
fprintf('Ass = AddBoundary(Ass, 2, ''No'', 308);\n');
fprintf('Bound2 = [0, 0, 1, 0, 0, 0];\n');
fprintf('Ass = SetBoundaryType(Ass, 2, Bound2);\n\n');
fprintf('%% 在第2段施加径向载荷\n');
fprintf('Ass = AddLoad(Ass, 3, ''No'', 102);\n');
fprintf('Load1 = [0, -3000, 0, 0, 0, 0];\n');
fprintf('Ass = SetLoad(Ass, 3, Load1);\n\n');

fprintf('%% 示例2：固定左端，右端受力\n');
fprintf('Ass = obj.output.Assembly;\n');
fprintf('Ass = AddBoundary(Ass, 1, ''No'', 301);\n');
fprintf('Bound1 = [1, 1, 1, 0, 0, 0];\n');
fprintf('Ass = SetBoundaryType(Ass, 1, Bound1);\n\n');
fprintf('%% 在第3段阶梯面施加轴向力\n');
fprintf('Ass = AddLoad(Ass, 2, ''No'', 307);\n');
fprintf('Load2 = [5000, 0, 0, 0, 0, 0];\n');
fprintf('Ass = SetLoad(Ass, 2, Load2);\n\n');

fprintf('%% 示例3：施加扭矩\n');
fprintf('Ass = obj.output.Assembly;\n');
fprintf('Ass = AddBoundary(Ass, 1, ''No'', 301);\n');
fprintf('Bound1 = [1, 1, 1, 1, 1, 1];\n');
fprintf('Ass = SetBoundaryType(Ass, 1, Bound1);\n\n');
fprintf('%% 在第1段外表面施加扭矩\n');
fprintf('Ass = AddLoad(Ass, 2, ''No'', 101);\n');
fprintf('Load3 = [0, 0, 0, 15000, 0, 0];\n');
fprintf('Ass = SetLoad(Ass, 2, Load3);\n\n');
fprintf('========================================\n');
