% Create a 500mm long, 50mm diameter solid shaft
% 创建长500mm、直径50mm的实心轴
%
% Author: Generated by Claude Code
% Date: 2026-01-31

clc
clear
close all

%% 轴参数定义
fprintf('========================================\n');
fprintf('轴参数定义\n');
fprintf('========================================\n');
fprintf('长度: 500 mm\n');
fprintf('外径: 50 mm\n');
fprintf('内径: 0 mm (实心)\n\n');

%% 输入参数
% 定义轴的几何参数
inputShaft.Length = 500;       % 总长度 [mm]
inputShaft.ID = [0, 0];        % 内径 [mm]，0表示实心
inputShaft.OD = [50, 50];      % 外径 [mm]，保持不变

%% 可选参数
paramsShaft = struct();
paramsShaft.Name = 'Shaft_500mm_D50mm';  % 轴名称
paramsShaft.Order = 1;          % 单元阶次：1=一阶，2=二阶
paramsShaft.E_Revolve = 40;     % 旋转划分数（圆周分段）
paramsShaft.Beam_N = 16;         % 梁截面圆周分段数
paramsShaft.N_Slice = 50;        % 切片数量
paramsShaft.Echo = 1;            % 打印信息

%% 创建轴对象
fprintf('========================================\n');
fprintf('创建轴对象...\n');
fprintf('========================================\n');
obj = shaft.Commonshaft(paramsShaft, inputShaft);

%% 求解
fprintf('========================================\n');
fprintf('求解中...\n');
fprintf('========================================\n');
obj = obj.solve();

%% 绘图
fprintf('========================================\n');
fprintf('绘制图形...\n');
fprintf('========================================\n');

% 2D截面图
fprintf('绘制2D截面...\n');
Plot2D(obj);

% 3D图形
fprintf('绘制3D模型...\n');
Plot3D(obj);

%% 网格信息
fprintf('========================================\n');
fprintf('网格统计信息\n');
fprintf('========================================\n');
fprintf('节点数: %d\n', size(obj.output.SolidMesh.Vert, 1));
fprintf('面数: %d\n', size(obj.output.SolidMesh.Face, 1));

%% 获取材料信息
fprintf('========================================\n');
fprintf('材料信息\n');
fprintf('========================================\n');
fprintf('材料名称: %s\n', obj.params.Material.Name);
fprintf('密度: %.2e kg/mm^3\n', obj.params.Material.Dens);
fprintf('弹性模量: %.2e MPa\n', obj.params.Material.E);
fprintf('泊松比: %.3f\n', obj.params.Material.v);
fprintf('热膨胀系数: %.2e /K\n', obj.params.Material.a);

%% 边界标记说明
fprintf('========================================\n');
fprintf('边界标记说明\n');
fprintf('========================================\n');
fprintf('101: 外表面\n');
fprintf('201: 内表面（无，因为ID=0）\n');
fprintf('301: 左端面 (x=0mm)\n');
fprintf('302: 右端面 (x=500mm)\n\n');

%% 输出STL文件（可选）
fprintf('========================================\n');
fprintf('输出STL文件...\n');
fprintf('========================================\n');
OutputSTL(obj);

%% 完成信息
fprintf('========================================\n');
fprintf('轴创建完成！\n');
fprintf('========================================\n');
fprintf('文件名: %s.stl\n', obj.params.Name);
fprintf('实体装配: 已创建\n');
fprintf('梁装配: 已创建\n');
fprintf('========================================\n');

%% 可选：导出ANSYS文件（如果需要）
fprintf('输出ANSYS文件...\n');
ANSYS_Output(obj.output.Assembly);
fprintf('ANSYS文件已生成\n');

%% 显示图形
figure('Position', [100, 100, 1200, 400]);

% 2D截面
subplot(1, 2, 1);
Plot(obj.output.Surface);
title('2D截面');
axis equal;

% 3D模型
subplot(1, 2, 2);
PlotFace(obj.output.SolidMesh);
title('3D实体模型');
axis equal;
