% Create stepped shaft from image analysis
% 根据图片分析创建4段阶梯实心轴
%
% 图片分析特征：
% - 4段阶梯轴
% - 从左到右直径：55 -> 38 -> 45 -> 58 mm
% - 各段长度：30 -> 85 -> 60 -> 40 mm
% - 总长度：215 mm
% - 全部实心（ID=0）
%
% Author: Generated by Claude Code
% Date: 2026-01-31

clc
clear
close all

%% 轴参数定义（从图片提取）
fprintf('========================================\n');
fprintf('轴参数定义（从图片提取）\n');
fprintf('========================================\n');
fprintf('类型: 4段阶梯实心轴\n');
fprintf('总长度: 215 mm\n');
fprintf('直径范围: 38-58 mm\n\n');

fprintf('各段参数：\n');
fprintf('  第1段: 长度=30mm, 外径=55mm\n');
fprintf('  第2段: 长度=85mm, 外径=38mm\n');
fprintf('  第3段: 长度=60mm, 外径=45mm\n');
fprintf('  第4段: 长度=40mm, 外径=58mm\n\n');

%% 输入参数
% 定义轴的几何参数（4段阶梯轴）
inputShaft.Length = [30; 115; 175; 215];      % 各段结束位置 [mm]
inputShaft.ID = [[0, 0]; [0, 0]; [0, 0]; [0, 0]];  % 全部实心
inputShaft.OD = [[55, 55]; [38, 38]; [45, 45]; [58, 58]];  % 各段外径 [mm]

%% 可选参数
paramsShaft = struct();
paramsShaft.Name = 'SteppedShaft_4Sections';  % 轴名称
paramsShaft.Order = 1;          % 单元阶次：1=一阶，2=二阶
paramsShaft.E_Revolve = 48;     % 旋转划分数（圆周分段，增加以获得更平滑的圆柱面）
paramsShaft.Beam_N = 16;         % 梁截面圆周分段数
paramsShaft.N_Slice = 50;        % 切片数量
paramsShaft.Meshsize = 3;         % 网格尺寸 [mm]，较小的值获得更精细的网格
paramsShaft.Echo = 1;            % 打印信息

%% 创建轴对象
fprintf('========================================\n');
fprintf('创建轴对象...\n');
fprintf('========================================\n');
obj = shaft.Commonshaft(paramsShaft, inputShaft);

%% 求解
fprintf('========================================\n');
fprintf('求解中...\n');
fprintf('========================================\n');
obj = obj.solve();

%% 绘图
fprintf('========================================\n');
fprintf('绘制图形...\n');
fprintf('========================================\n');

% 2D截面图
fprintf('绘制2D截面...\n');
Plot2D(obj);

% 3D图形（显示整个轴）
fprintf('绘制3D模型...\n');
Plot3D(obj);

% 绘制每一段的外表面
fprintf('绘制各段外表面...\n');
for i = 1:4
    Plot3D(obj, 'faceno', 100 + i);
end

%% 网格信息
fprintf('========================================\n');
fprintf('网格统计信息\n');
fprintf('========================================\n');
fprintf('节点数: %d\n', size(obj.output.SolidMesh.Vert, 1));
fprintf('面数: %d\n', size(obj.output.SolidMesh.Face, 1));
fprintf('切片数: %d\n', size(obj.output.Node, 1));

%% 截面信息
fprintf('========================================\n');
fprintf('轴截面信息（沿轴向）\n');
fprintf('========================================\n');
fprintf('位置(mm)\t内径(mm)\t外径(mm)\n');
fprintf('----------------------------------------\n');
for i = 1:5:size(obj.output.Node, 1)
    fprintf('%.1f\t\t%.2f\t\t%.2f\n', obj.output.Node(i), obj.output.ID(i), obj.output.OD(i));
end

%% 获取材料信息
fprintf('========================================\n');
fprintf('材料信息\n');
fprintf('========================================\n');
fprintf('材料名称: %s\n', obj.params.Material.Name);
fprintf('密度: %.2e kg/mm^3\n', obj.params.Material.Dens);
fprintf('弹性模量: %.2e MPa\n', obj.params.Material.E);
fprintf('泊松比: %.3f\n', obj.params.Material.v);
fprintf('热膨胀系数: %.2e /K\n', obj.params.Material.a);

%% 边界标记说明
fprintf('========================================\n');
fprintf('边界标记说明\n');
fprintf('========================================\n');
fprintf('101: 第1段外表面\n');
fprintf('102: 第2段外表面\n');
fprintf('103: 第3段外表面\n');
fprintf('104: 第4段外表面\n');
fprintf('201-204: 内表面（无，因为ID=0）\n');
fprintf('301: 左端面 (x=0mm)\n');
fprintf('305-307: 各段阶梯面\n');
fprintf('308: 右端面 (x=215mm)\n\n');

%% 输出STL文件
fprintf('========================================\n');
fprintf('输出STL文件...\n');
fprintf('========================================\n');
OutputSTL(obj);

%% 完成信息
fprintf('========================================\n');
fprintf('轴创建完成！\n');
fprintf('========================================\n');
fprintf('轴名称: %s\n', obj.params.Name);
fprintf('STL文件: %s.stl\n', obj.params.Name);
fprintf('========================================\n');

%% 创建综合视图
figure('Position', [50, 50, 1400, 400]);

% 2D截面
subplot(1, 3, 1);
Plot(obj.output.Surface);
title('2D截面图');
axis equal;
grid on;

% 3D模型
subplot(1, 3, 2);
PlotFace(obj.output.SolidMesh);
title('3D实体模型');
axis equal;
grid on;
view(3);

% 3D模型（不同视角）
subplot(1, 3, 3);
PlotFace(obj.output.SolidMesh);
title('3D实体模型（侧视图）');
axis equal;
grid on;
view(0, 0);

%% 生成截面图
figure('Position', [100, 100, 1000, 600]);
x = obj.output.Node;
y_outer = obj.output.OD / 2;
y_inner = obj.output.ID / 2;

% 绘制外径变化
subplot(2, 1, 1);
plot(x, y_outer, 'b-o', 'LineWidth', 2, 'MarkerSize', 6);
hold on;
plot(x, y_inner, 'r--', 'LineWidth', 1.5);
grid on;
xlabel('轴向位置 (mm)');
ylabel('半径 (mm)');
title('轴直径沿轴向变化');
legend('外径', '内径', 'Location', 'best');
axis tight;

% 绘制外径
subplot(2, 1, 2);
plot(x, obj.output.OD, 'b-o', 'LineWidth', 2, 'MarkerSize', 6);
grid on;
xlabel('轴向位置 (mm)');
ylabel('外径 (mm)');
title('外径沿轴向分布');
axis tight;

%% 边界条件示例（可选）
fprintf('========================================\n');
fprintf('边界条件示例代码\n');
fprintf('========================================\n');
fprintf('%% 固定左端面\n');
fprintf('Ass = obj.output.Assembly;\n');
fprintf('Ass = AddBoundary(Ass, 1, ''No'', 301);\n');
fprintf('Bound1 = [1, 1, 1, 0, 0, 0];\n');
fprintf('Ass = SetBoundaryType(Ass, 1, Bound1);\n\n');

fprintf('%% 在右端面施加力\n');
fprintf('Ass = AddLoad(Ass, 1, ''No'', 308);\n');
fprintf('Load1 = [0, -5000, 0, 0, 0, 0];\n');
fprintf('Ass = SetLoad(Ass, 1, Load1);\n\n');

fprintf('%% 在第1段外表面施加扭矩\n');
fprintf('Ass = AddLoad(Ass, 1, ''No'', 101);\n');
fprintf('Load2 = [0, 0, 0, 10000, 0, 0];\n');
fprintf('Ass = SetLoad(Ass, 1, Load2);\n');
fprintf('========================================\n');
