function obj=OutputCatia(obj,varargin)
% OutputCatia - 输出轴的几何模型到 CATIA
% 直接使用 pycatia 连接 CATIA V5 创建轴的几何体
% Author: Xie Yu
%
% Inputs:
%   obj           - Commonshaft 对象
%   varargin      - 可选参数对
%     'FileName'   - 保存的 CATPart 文件名 (默认 'Shaft_from_Baffalo')
%     'SavePath'   - 保存路径 (默认当前目录)
%     'E_Revolve'  - 旋转划分数 (默认 obj.params.E_Revolve)
%
% Examples:
%   OutputCatia(obj)                    % 连接 CATIA 并创建轴
%   OutputCatia(obj,'FileName','MyShaft') % 自定义文件名

%% 解析输入参数
p=inputParser;
addParameter(p,'FileName','Shaft_from_Baffalo');
addParameter(p,'SavePath',pwd);
addParameter(p,'E_Revolve',obj.params.E_Revolve);
parse(p,varargin{:});
opt=p.Results;

%% 准备轴的几何数据
segments=PrepareGeometry(obj);

%% 生成 Python 脚本（用于参考和独立运行）
pythonScript=GeneratePythonScript(obj,opt,segments);
scriptFile=fullfile(opt.SavePath,[opt.FileName,'_catia.py']);
fid=fopen(scriptFile,'w');
fwrite(fid,pythonScript);
fclose(fid);
fprintf('Python script saved to: %s\n',scriptFile);

%% 连接 CATIA 并创建模型
try
    CreateCatiaModel(obj,opt,segments);
    fprintf('Successfully created CATIA model: %s\n',opt.FileName);
catch ME
    fprintf('Warning: Could not connect to CATIA.\n');
    fprintf('Error: %s\n',ME.message);
    fprintf('You can run the Python script manually.\n');
end

end

function segments=PrepareGeometry(obj)
% 准备轴的几何数据

nSegment=size(obj.input.Length,1);
segments=struct();

for i=1:nSegment
    seg=struct();
    seg.startPos=obj.input.Length(i,1);
    seg.endPos=obj.input.Length(i,2);
    seg.startID=obj.input.ID(i,1);
    seg.endID=obj.input.ID(i,2);
    seg.startOD=obj.input.OD(i,1);
    seg.endOD=obj.input.OD(i,2);
    segments(i)=seg;
end

end

function pythonScript=GeneratePythonScript(obj,opt,segments)
% 生成 pycatia Python 脚本

pythonScript=sprintf(['#!/usr/bin/env python\n' ...
    '# -*- coding: utf-8 -*-\n' ...
    '"""\n' ...
    'CATIA Shaft Geometry Generator\n' ...
    'Generated by Baffalo Framework\n' ...
    '"""\n\n' ...
    'from pycatia import catia\n\n']);

% 主函数
pythonScript=sprintf(['%s\n' ...
    'def create_shaft(segments, file_name):\n' ...
    '    """Create shaft geometry from segments."""\n\n' ...
    '    # Connect to CATIA\n' ...
    '    caa = catia()\n' ...
    '    print(f"Connected to CATIA: {caa.full_name}")\n\n' ...
    '    # Create new part document\n' ...
    '    doc = caa.documents.add("Part")\n' ...
    '    part = doc.part\n' ...
    '    body = part.bodies.add("Body")\n\n' ...
    '    # Get origin and XY plane\n' ...
    '    origin = part.origin_elements\n' ...
    '    xy_plane = origin.plane_xy\n\n'],pythonScript);

% 添加每个段
for i=1:numel(segments)
    seg=segments(i);
    pythonScript=sprintf(['%s    # ===== Segment %d =====\n' ...
        '    sketch = body.sketches.add(xy_plane)\n' ...
        '    factory_2d = sketch.open_edition()\n\n'],pythonScript,i);

    % 外轮廓点
    if seg.startID > 0 || seg.endID > 0
        % 空心段
        pythonScript=sprintf(['%s    # Create profile with hole\n' ...
        '    half_start_od = %f / 2\n' ...
        '    half_end_od = %f / 2\n' ...
        '    half_start_id = %f / 2\n' ...
        '    half_end_id = %f / 2\n\n'],pythonScript,seg.startOD,seg.endOD,seg.startID,seg.endID);
    else
        % 实心段
        pythonScript=sprintf(['%s    # Create solid segment profile\n' ...
        '    half_start_od = %f / 2\n' ...
        '    half_end_od = %f / 2\n\n'],pythonScript,seg.startOD,seg.endOD);
    end
end

% 关闭草图编辑并创建拉伸
pythonScript=sprintf(['%s    sketch.close_edition()\n\n' ...
    '    # Create pad feature\n' ...
    '    shape_factory = part.shape_factory\n' ...
    '    pad = shape_factory.add_new_pad(sketch, total_depth)\n\n' ...
    '    part.update()\n' ...
    '    return doc\n\n' ...
    'def main():\n' ...
    '    """Main entry point."""\n' ...
    '    file_name = "%s"\n\n'],pythonScript,opt.FileName);

% 添加 segments 数据
for i=1:numel(segments)
    seg=segments(i);
    pythonScript=sprintf(['%s    segments = [\n'],pythonScript);
    pythonScript=sprintf(['%s        {\n' ...
        '            "start_pos": %f,\n' ...
        '            "end_pos": %f,\n' ...
        '            "start_od": %f,\n' ...
        '            "end_od": %f,\n' ...
        '            "start_id": %f,\n' ...
        '            "end_id": %f\n' ...
        '        }%s\n'],pythonScript,seg.startPos,seg.endPos,seg.startOD,seg.endOD,seg.startID,seg.endID, ...
        char(i<numel(segments)',',' else '' end));
end

pythonScript=sprintf(['%s    ]\n\n' ...
    '    doc = create_shaft(segments, file_name)\n' ...
    '    doc.save_as(file_name)\n' ...
    '    print(f"Shaft saved to: {file_name}")\n\n' ...
    'if __name__ == "__main__":\n' ...
    '    main()\n'],pythonScript);

end

function CreateCatiaModel(obj,opt,segments)
% 使用 pycatia 直接连接 CATIA 并创建轴模型

% 检查 Python 环境
pe = pyenv;
if pe.Status ~= "Loaded"
    error('Python engine not loaded. Use: pyenv(Version,"path/to/python")');
end

% 导入 pycatia
pycatia = py.importlib('pycatia');

% 连接 CATIA (注意: pycatia.catia() 是正确的类名)
caa = pycatia.catia();
fprintf('Connected to CATIA: %s\n', char(caa.full_name));

% 创建新零件文档
doc = caa.documents.add("Part");
part = doc.part;
body = part.bodies.add("Body");

% 获取 XY 平面
origin = part.origin_elements;
xy_plane = origin.plane_xy;

% 创建每个段
for i = 1:numel(segments)
    seg = segments(i);

    % 创建草图
    sketch = body.sketches.add(xy_plane);

    % 打开草图编辑
    factory_2d = sketch.open_edition();

    % 计算半径
    half_start_od = double(seg.startOD / 2);
    half_end_od = double(seg.endOD / 2);
    half_start_id = double(seg.startID / 2);
    half_end_id = double(seg.endID / 2);

    % 创建外轮廓线 (从 startPos,halfStartOD 到 endPos,halfEndOD)
    factory_2d.create_line(seg.startPos, half_start_od, seg.endPos, half_end_od);
    factory_2d.create_line(seg.endPos, half_end_od, seg.endPos, half_end_id);
    factory_2d.create_line(seg.endPos, half_end_id, seg.startPos, half_start_id);
    factory_2d.create_line(seg.startPos, half_start_id, seg.startPos, half_start_od);

    % 关闭草图编辑
    sketch.close_edition();

    % 创建拉伸特征
    shape_factory = part.shape_factory;
    pad = shape_factory.add_new_pad(sketch, seg.endPos - seg.startPos);
    part.update();
end

% 保存零件
output_file = fullfile(opt.SavePath, [opt.FileName, '.CATPart']);
doc.save_as(output_file);
fprintf('CATIA model saved to: %s\n', output_file);

end
