function obj=geom_patch(obj,varargin)
% geom_patch Display data as patch
%

p=inputParser;
addParameter(p,'dodge',0);
addParameter(p,'alpha',1);
addParameter(p,'face_alpha',1);
addParameter(p,'edge_alpha',1);
addParameter(p,'face_normal',0);
addParameter(p,'edgecolor',[.2,.2,.2]);
parse(p,varargin{:});

obj.geom=vertcat(obj.geom,{@(dobj,dd)my_patch(dobj,dd,p.Results)});
obj.results.geom_patch_handle={};
end


function hndl=my_patch(obj,draw_data,params)
if isempty(obj.aes.facecolor)

    for k=1:length(draw_data.vertices)
        if isempty(draw_data.pointdata)
            hndl=patch('faces',draw_data.faces{k,1},...
                'vertices',draw_data.vertices{k,1}, ...
                'facecolor',draw_data.color, ...
                'edgecolor',params.edgecolor,...
                'lineWidth',draw_data.line_size,...
                'FaceAlpha',params.face_alpha,...
                'EdgeAlpha',params.edge_alpha) ;
        else
            hndl=patch('faces',draw_data.faces{k,1},...
                'vertices',draw_data.vertices{k,1}, ...
                'facecolor','interp',...
                'edgecolor',params.edgecolor,...
                'lineWidth',draw_data.line_size,...
                'FaceAlpha',params.face_alpha,...
                'EdgeAlpha',params.edge_alpha,...
                'FaceVertexCData',draw_data.pointdata{k,1}) ;
        end
    end
else
    for k=1:length(draw_data.vertices)
        [cc,~,ic]=unique(draw_data.facemap{k,1},'rows');
        for i=1:size(cc,1)
             ii=ic==i;
             if isempty(draw_data.pointdata)
                 hndl=patch('faces',draw_data.faces{k,1}(ii,:),...
                     'vertices',draw_data.vertices{k,1},...
                     'facecolor',cc(i,:),...
                     'edgecolor',params.edgecolor,...
                     'lineWidth',draw_data.line_size,...
                     'FaceAlpha',params.face_alpha,...
                     'EdgeAlpha',params.edge_alpha) ;
              else
                  hndl=patch('faces',draw_data.faces{k,1}(ii,:),...
                      'vertices',draw_data.vertices{k,1},...
                      'facecolor','interp',...
                      'edgecolor',params.edgecolor,...
                      'lineWidth',draw_data.line_size,...
                      'FaceAlpha',params.face_alpha,...
                      'EdgeAlpha',params.edge_alpha,...
                      'FaceVertexCData',draw_data.pointdata{k,1}) ;
              end

        end
    end
end

if params.face_normal==1
    Face=cell2mat(draw_data.faces);
    Vert=cell2mat(draw_data.vertices);
    patchNormPlot(Face,Vert);
end

set_alpha(hndl,params.alpha,1);
obj.results.geom_patch_handle{obj.result_ind,1}=hndl;
end