function obj=geom_quiver3(obj,varargin)
% geom_quiver3 Display data as quivers
%

p=inputParser;
addParameter(p,'dodge',0);
addParameter(p,'alpha',1);
addParameter(p,'AutoScaleFactor',0.9)
addParameter(p,'Alignment','tail')
parse(p,varargin{:});

obj.geom=vertcat(obj.geom,{@(dobj,dd)my_quiver3(dobj,dd,p.Results)});
obj.results.geom_quiver3_handle={};
end


function hndl=my_quiver3(obj,draw_data,params)

if obj.continuous_color_options.active

    obj.plot_lim.maxc(obj.current_row,obj.current_column)=max(obj.plot_lim.maxc(obj.current_row,obj.current_column),max(comb(draw_data.continuous_color)));
    obj.plot_lim.minc(obj.current_row,obj.current_column)=min(obj.plot_lim.minc(obj.current_row,obj.current_column),min(comb(draw_data.continuous_color)));

    if iscell(draw_data.x)
        for k=1:length(draw_data.x)
            if iscell(draw_data.continuous_color) %Within-line continuous color given
                hndl=quiver3(draw_data.x{k},draw_data.y{k},draw_data.z{k},...
                    draw_data.u{k},draw_data.v{k},draw_data.w{k},...
                    'Color',draw_data.continuous_color{k},...
                    'lineWidth',draw_data.line_size,...
                    'LineStyle',draw_data.line_style,...
                    'AutoScaleFactor',params.AutoScaleFactor,...
                    'Alignment',params.Alignment);
            else %Per-line continuous color given
                hndl=quiver3(draw_data.x{k},draw_data.y{k},draw_data.z{k},...
                    draw_data.u{k},draw_data.v{k},draw_data.w{k},...
                    'Color',repmat(draw_data.continuous_color(k),length(draw_data.x{k}),1),...
                    'lineWidth',draw_data.line_size,...
                    'LineStyle',draw_data.line_style,...
                    'AutoScaleFactor',params.AutoScaleFactor,...
                    'Alignment',params.Alignment);
            end
        end
    else
        hndl=quiver3(draw_data.x,draw_data.y,draw_data.z,...
            draw_data.u,draw_data.v,draw_data.w,...
            'Color',draw_data.continuous_color,...
            'lineWidth',draw_data.line_size,...
            'LineStyle',draw_data.line_style,...
            'AutoScaleFactor',params.AutoScaleFactor,...
            'Alignment',params.Alignment);
    end
else
    hndl=quiver3(combnan(draw_data.x),combnan(draw_data.y),combnan(draw_data.z),...
        combnan(draw_data.u),combnan(draw_data.v),combnan(draw_data.w),...
        'LineStyle',draw_data.line_style,...
        'lineWidth',draw_data.line_size,...
        'Color',draw_data.color,...
        'AutoScaleFactor',params.AutoScaleFactor,...
        'Alignment',params.Alignment);
end
    
set_alpha(hndl,params.alpha,1);

obj.results.geom_quiver3_handle{obj.result_ind,1}=hndl;
end